"""empty message

Revision ID: ff3f63dd018a
Revises: 937d7312f870
Create Date: 2017-08-25 15:56:14.330932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3f63dd018a'
down_revision = '937d7312f870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucketlist_item_name', sa.String(length=255), nullable=True),
    sa.Column('bucketlist_item_description', sa.String(length=255), nullable=True),
    sa.Column('bucketlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucketlist_id'], ['bucketlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('activity_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('activity_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bucketlist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bucketlist_id'], ['bucketlist.id'], name='activity_bucketlist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='activity_pkey')
    )
    op.drop_table('bucketlist_item')
    # ### end Alembic commands ###
